### ISSUE TITLE
Paste from terminal

### ISSUE THREAD

**Issue by kyx0r** [aligrudi/neatvi#18]
May not really be an issue for everyone, however if your terminal happen to support pasting like st does, you will find that doing so in neatvi will totally mess up the indenting, and the bigger the paste, the more shifted to the right text will become. I am not a big fan of that, so if you want to disable this just set 
`
xai = 0
`
in ex.c

Though since technically pasting is the same as just dumping text character by character to get the right output vi has to be in insert mode. One thing I don't like though is that it does preserve the formatting, it seems like the terminal copies blanks as spaces and so the code will end up formatted with spaces instead of tabs. I will patch this out at some point in my personal version of neatvi.

**Comment by cjwagenius** [comment]
Just 'set noai' before pasting.

It _does_ preserve formatting. You're probably copying from a terminal, thus getting spaces with you instead of tabs. It's messy. Open the file you want to copy from in another buffer instead and use yank. It's most convenient. If that's impossible, replace preceding spaces with tabs.

    :%s/^ {8}/[a tab here]/g

You'll also have to remove trailing spaces.

    :%s/ +$//g

 :)

 Have a nice day.

/cjw

19 nov. 2020 07:34 av notifications@github.com:

**Comment by FAETHER** [comment]
Thanks, this is actually a really nice suggestion that fits my work flow well enough. Somewhere in the similar area I was thinking in, though I did totally forget about the regex operations. They make this easier to implement, so I'll just make new keybinds for this in my build.
