### ISSUE TITLE
"cw" and last word of line

### ISSUE THREAD

**Issue by polluks** [aligrudi/neatvi#46]
Hi!
The next line is affected, this behavior doesn't seem standard to me.

**Comment by aligrudi** [comment]
Hi Stefan,

Stefan ***@***.***> wrote:
> The next line is affected, this behavior doesn't seem standard to me.

The problem is that the behaviour of cw in Neatvi is not compatible
with the standard vi.  In vi, cw is handled as a special case; it is
not equivalent to "change till the destination of w movement".  Neatvi
does not do that and w in cw is handled as an ordinary movement.

	Ali

**Comment by polluks** [comment]
Aha, more vi than vi :-)
